// <auto-generated />
using System;
using App.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228012224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Api.Models.ExpenseAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("expense_accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("23e385a1-0100-48e2-9e28-39927c49a665"),
                            CreatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1818),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Wise USD",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1821)
                        },
                        new
                        {
                            Id = new Guid("46b8e90f-0a8c-4a4d-b21c-20475bdd0c6a"),
                            CreatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1823),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Citi USD",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1823)
                        },
                        new
                        {
                            Id = new Guid("e61211ae-aa2d-4426-8e31-a4c44deffb93"),
                            CreatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1824),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Cash USD",
                            Type = "Cash",
                            UpdatedAt = new DateTime(2026, 2, 28, 1, 22, 23, 885, DateTimeKind.Utc).AddTicks(1825)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
