// <auto-generated />
using System;
using App.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228015137_UpdateMonthSeed")]
    partial class UpdateMonthSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Api.Models.ExpenseAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("expense_accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "CASH $",
                            Type = "Cash",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Tarjeta Visa",
                            Type = "CC",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Tarjeta Amex",
                            Type = "CC",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Santander $",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Citi USD",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Api.Models.FxRateMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MonthId")
                        .IsUnique();

                    b.ToTable("fx_rate_months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            BaseCurrency = "USD",
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            QuoteCurrency = "ARS",
                            Rate = 1450m
                        });
                });

            modelBuilder.Entity("App.Api.Models.Month", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            MonthNumber = 2,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("App.Api.Models.FxRateMonth", b =>
                {
                    b.HasOne("App.Api.Models.Month", "Month")
                        .WithOne("FxRate")
                        .HasForeignKey("App.Api.Models.FxRateMonth", "MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("App.Api.Models.Month", b =>
                {
                    b.Navigation("FxRate");
                });
#pragma warning restore 612, 618
        }
    }
}
