// <auto-generated />
using System;
using App.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301014718_AddVariableExpenses")]
    partial class AddVariableExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Api.Models.CardBalanceMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("OtherExpensesArs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OtherExpensesUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("card_balance_months", (string)null);
                });

            modelBuilder.Entity("App.Api.Models.CardExpenseMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardInstallmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Installment")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardInstallmentId");

                    b.ToTable("card_expense_months", (string)null);
                });

            modelBuilder.Entity("App.Api.Models.CardInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<int>("Payments")
                        .HasColumnType("integer");

                    b.Property<int>("StartingMonth")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId");

                    b.ToTable("card_installments", (string)null);
                });

            modelBuilder.Entity("App.Api.Models.ExpenseAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("expense_accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "CASH $",
                            Type = "Cash",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Tarjeta Visa",
                            Type = "CC",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Tarjeta Amex",
                            Type = "CC",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            IsActive = true,
                            Name = "Santander $",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Citi USD",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Api.Models.FixedExpenseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExpireDay")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId");

                    b.ToTable("fixed_expense_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000004"),
                            ExpireDay = 20,
                            IsActive = true,
                            Name = "Osde"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000004"),
                            ExpireDay = 10,
                            IsActive = true,
                            Name = "Arba"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000004"),
                            ExpireDay = 15,
                            IsActive = true,
                            Name = "Contador"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000004"),
                            ExpireDay = 20,
                            IsActive = true,
                            Name = "Impuestos"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000004"),
                            ExpireDay = 22,
                            IsActive = true,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ExpireDay = 10,
                            IsActive = true,
                            Name = "Alquiler"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ExpireDay = 8,
                            IsActive = true,
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ExpireDay = 10,
                            IsActive = true,
                            Name = "Gimnasio"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Seguro Moto"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Seguro Auto"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ARS",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Hbo"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Youtube"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Google Drive"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            ExpenseAccountId = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Netflix"
                        });
                });

            modelBuilder.Entity("App.Api.Models.FixedExpenseMonthEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("FixedExpenseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.HasIndex("FixedExpenseDefinitionId", "MonthId")
                        .IsUnique();

                    b.ToTable("fixed_expense_month_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            Amount = 235930m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000001"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            Amount = 437000m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000004"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            Amount = 49000m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000008"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            Amount = 95000m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000007"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            Amount = 1373000m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000006"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            Amount = 92000m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000005"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000007"),
                            Amount = 78285m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000009"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000008"),
                            Amount = 155358.33m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000010"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000009"),
                            Amount = 8628.35m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000011"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000010"),
                            Amount = 0m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000012"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000011"),
                            Amount = 0m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000013"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000012"),
                            Amount = 0m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000014"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000013"),
                            Amount = 0m,
                            FixedExpenseDefinitionId = new Guid("44444444-0000-0000-0000-000000000015"),
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Api.Models.FxRateMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MonthId")
                        .IsUnique();

                    b.ToTable("fx_rate_months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            BaseCurrency = "USD",
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            QuoteCurrency = "ARS",
                            Rate = 1450m
                        });
                });

            modelBuilder.Entity("App.Api.Models.Month", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            MonthNumber = 2,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("App.Api.Models.SavingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("saving_accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Santander",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Citi",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Wise",
                            Type = "Bank",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true,
                            Name = "Cash",
                            Type = "Cash",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("App.Api.Models.SavingAccountMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SavingAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.HasIndex("SavingAccountId", "MonthId")
                        .IsUnique();

                    b.ToTable("saving_account_months", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000001"),
                            Balance = 20547.16m,
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            SavingAccountId = new Guid("66666666-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000002"),
                            Balance = 32027.61m,
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            SavingAccountId = new Guid("66666666-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000003"),
                            Balance = 0m,
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            SavingAccountId = new Guid("66666666-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000004"),
                            Balance = 12745m,
                            MonthId = new Guid("22222222-0000-0000-0000-000000000003"),
                            SavingAccountId = new Guid("66666666-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("App.Api.Models.SavingAccountMonthTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SavingAccountMonthId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SavingAccountMonthId");

                    b.ToTable("saving_account_month_transactions", (string)null);
                });

            modelBuilder.Entity("App.Api.Models.VariableExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("variable_expenses", (string)null);
                });

            modelBuilder.Entity("App.Api.Models.CardBalanceMonth", b =>
                {
                    b.HasOne("App.Api.Models.ExpenseAccount", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseAccount");
                });

            modelBuilder.Entity("App.Api.Models.CardExpenseMonth", b =>
                {
                    b.HasOne("App.Api.Models.CardInstallment", "CardInstallment")
                        .WithMany("CardExpenseMonths")
                        .HasForeignKey("CardInstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInstallment");
                });

            modelBuilder.Entity("App.Api.Models.CardInstallment", b =>
                {
                    b.HasOne("App.Api.Models.ExpenseAccount", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseAccount");
                });

            modelBuilder.Entity("App.Api.Models.FixedExpenseDefinition", b =>
                {
                    b.HasOne("App.Api.Models.ExpenseAccount", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseAccount");
                });

            modelBuilder.Entity("App.Api.Models.FixedExpenseMonthEntry", b =>
                {
                    b.HasOne("App.Api.Models.FixedExpenseDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("FixedExpenseDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Api.Models.Month", "Month")
                        .WithMany()
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Month");
                });

            modelBuilder.Entity("App.Api.Models.FxRateMonth", b =>
                {
                    b.HasOne("App.Api.Models.Month", "Month")
                        .WithOne("FxRate")
                        .HasForeignKey("App.Api.Models.FxRateMonth", "MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("App.Api.Models.SavingAccountMonth", b =>
                {
                    b.HasOne("App.Api.Models.Month", "Month")
                        .WithMany()
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Api.Models.SavingAccount", "SavingAccount")
                        .WithMany()
                        .HasForeignKey("SavingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");

                    b.Navigation("SavingAccount");
                });

            modelBuilder.Entity("App.Api.Models.SavingAccountMonthTransaction", b =>
                {
                    b.HasOne("App.Api.Models.SavingAccountMonth", "SavingAccountMonth")
                        .WithMany()
                        .HasForeignKey("SavingAccountMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingAccountMonth");
                });

            modelBuilder.Entity("App.Api.Models.VariableExpense", b =>
                {
                    b.HasOne("App.Api.Models.ExpenseAccount", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseAccount");
                });

            modelBuilder.Entity("App.Api.Models.CardInstallment", b =>
                {
                    b.Navigation("CardExpenseMonths");
                });

            modelBuilder.Entity("App.Api.Models.Month", b =>
                {
                    b.Navigation("FxRate");
                });
#pragma warning restore 612, 618
        }
    }
}
